INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 1, 1, 285.3, 0,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 2, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 2, 2, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 3, 1, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 4, 1, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 4, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 5, 1, 269.7, 0,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 5, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 5, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 5, 4, 269.7, 0,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 6, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 6, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 6, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 7, 1, 324.4, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 7, 2, 324.4, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 8, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 8, 2, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 8, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 8, 4, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 9, 1, 324.4, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 10, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 11, 1, 269.7, 0,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 12, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 12, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 12, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 12, 4, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 13, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 13, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 13, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 14, 1, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 14, 2, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 14, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 14, 4, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 15, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 15, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 15, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 15, 4, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 16, 1, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 16, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 16, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 16, 4, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 17, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 17, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 17, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 17, 4, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 18, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 19, 1, 324.4, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 19, 2, 324.4, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 19, 3, 324.4, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 19, 4, 324.4, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 19, 5, 324.4, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 19, 6, 324.4, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 20, 1, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 20, 2, 269.7, 1,'lower');


INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 247, 1, 269.7, -2,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 247, 2, 269.7, -2,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 247, 3, 269.7, -2,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 247, 4, 269.7, -2,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 248, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 249, 1, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 249, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 250, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 250, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 250, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 251, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 251, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 251, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 252, 1, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 253, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 253, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 253, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 254, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 255, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 256, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 256, 2, 269.7, -2,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 256, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 257, 1, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 258, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 258, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 259, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 259, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 259, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 259, 4, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 259, 5, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 260, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 260, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 260, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 260, 4, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 261, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 262, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 262, 2, 269.7, 0,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 262, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 262, 4, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 263, 1, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 264, 1, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 265, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 265, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 265, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 266, 1, 269.7, 1,'faster');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 266, 2, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 266, 3, 269.7, 1,'lower');
INSERT INTO charger (chargerId, stationId, chargerNum, kwPrice, status, speed ) VALUES (charger_SEQ.NEXTVAL, 266, 4, 269.7, 0,'lower');


insert into CHARGER values (CHARGER_SEQ.nextval,73,1,324.4,-1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,344,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,345,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,345,2,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,345,3,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,346,1,460,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,346,2,460,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,347,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,347,2,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,348,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,348,2,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,348,3,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,348,4,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,348,5,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,349,1,324.4,-1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,349,2,324.4,-1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,350,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,350,2,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,351,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,351,2,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,352,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,353,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,358,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,359,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,360,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,361,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,362,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,363,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,364,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,365,1,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,365,2,324.4,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,366,1,324.4,1,'faster');



insert into CHARGER values (CHARGER_SEQ.nextval,156,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,156,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,157,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,157,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,158,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,158,2,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,158,3,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,159,1,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,159,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,160,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,160,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,160,3,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,161,1,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,161,2,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,162,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,162,2,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,162,3,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,163,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,163,2,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,164,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,164,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,165,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,165,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,166,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,166,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,166,3,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,167,1,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,167,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,167,3,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,167,4,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,167,5,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,168,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,168,2,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,168,3,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,169,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,169,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,169,3,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,169,4,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,169,5,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,169,6,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,169,7,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,170,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,170,2,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,170,3,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,170,4,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,170,5,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,170,6,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,170,7,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,171,1,380,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,171,2,380,1,'faster');
insert into CHARGER values (CHARGER_SEQ.nextval,172,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,172,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,173,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,173,2,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,173,3,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,174,1,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,174,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,174,3,380,0,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,175,1,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,175,2,380,1,'lower');
insert into CHARGER values (CHARGER_SEQ.nextval,175,3,380,0,'lower');